name: Create Release

on:
  workflow_run:
    workflows: ["Tests"]
    permissions:
      contents: write
  release:
    types: [created]

env:
  CRATE_NAME: cat-downloader
  GITHUB_TOKEN: ${{ github.token }}
  RUST_BACKTRACE: 1

jobs:
  release:
    name: Release - ${{ matrix.platform.os_name }}
    strategy:
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-musl

          - os_name: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin

          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-gnu

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build executable
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: cat_show_downloader
          target: ${{ matrix.platform.target }}
          changes-file: "CHANGELOG.md"
